# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3lljB9SEduLbdlkmvBBFYp4kTLzRAb5
"""

def calculate_bonus_points(number):
    if number <= 100:
        bonus = 5
    elif 100 < number <= 1000:
        bonus = number * 0.2
    else:
        bonus = number * 0.1
    if number % 2 == 0:
        bonus += 1
    if str(number)[-1] == '5':
        bonus += 2
    total_points = number + bonus
    return bonus, total_points
number = int(input("Тоо оруулна уу: "))
bonus, total_points = calculate_bonus_points(number)
print(bonus)
print(total_points)

for number in range (-31, 13, 6):
print(f"number: {number}")

uzeg = 5.80
marker = 7.20
nuntag = 1.20
num_uzeg = int(input())
num_marker = int(input())
num_nuntag = int(input())
total_cost = (num_uzeg * uzeg) + (num_marker * marker) + (num_nuntag * nuntag)
hungulult = 13
discount = total_cost * (hungulult / 100)
final_cost = total_cost - discount
print(hungulult)
print(round(final_cost, 3))

import math
shape = input().strip().lower()
if shape == "square":
    side = float(input())
    area = side ** 2
elif shape == "rectangle":
    length = float(input())
    width = float(input())
    area = length * width
elif shape == "circle":
    radius = float(input())
    area = math.pi * (radius ** 2)
elif shape == "triangle":
    base = float(input())
    height = float(input())
    area = 0.5 * base * height
else:
    print("Буруу оролт!")
    exit()
print(f"{area:.3f}")

def format_time(total_seconds):
    minutes = total_seconds // 60
    seconds = total_seconds % 60
    return f"{minutes:02}:{seconds:02}"
timings = [135, 67, 150, 14, 12, 10]
total_seconds = sum(timings)
formatted_time = format_time(total_seconds)
print("Нийт Цаг:", formatted_time)